using System.Reflection;
using System.Runtime.Loader;

namespace JinnDev.JCMU.ConsoleBed.Runtime;

/// <summary>
/// A specialized memory isolation container for JCMU Addons.
/// Ensures that an addon's dependencies are loaded from its specific installation folder,
/// preventing DLL Hell and version conflicts with the Core engine or other addons.
/// </summary>
public class PluginLoadContext : AssemblyLoadContext
{
    private readonly AssemblyDependencyResolver _resolver;

    /// <summary>
    /// Initializes a new Load Context for a specific addon.
    /// </summary>
    /// <param name="pluginPath">The absolute path to the addon's primary compiled DLL.</param>
    public PluginLoadContext(string pluginPath)
        // isCollectible: true allows this entire memory space to be unloaded and garbage collected
        // after the addon finishes executing, freeing up system RAM.
        : base(isCollectible: true)
    {
        // The resolver parses the .deps.json file generated by 'dotnet publish'
        // to understand exactly which dependencies the addon was compiled against.
        _resolver = new AssemblyDependencyResolver(pluginPath);
    }

    /// <summary>
    /// Overrides the default .NET assembly resolution behavior.
    /// When the addon asks for a type (e.g., "Newtonsoft.Json"), this method is triggered.
    /// </summary>
    protected override Assembly? Load(AssemblyName assemblyName)
    {
        // Check if the Core (Default context) already has this assembly loaded.
        // This effectively "Auto-shares" the SDK, Monads, and even standard 
        // Microsoft extensions like Logging or DI if the Core is using them.
        var alreadyLoaded = AssemblyLoadContext.Default.Assemblies
            .FirstOrDefault(a => a.GetName().Name == assemblyName.Name);

        if (alreadyLoaded != null)
        {
            return null; // Defer to the Core's version
        }

        // Check if the requested assembly exists in the addon's specific folder.
        string? assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);

        if (assemblyPath != null)
        {
            // If we found it locally, load it directly into this isolated context.
            return LoadFromAssemblyPath(assemblyPath);
        }

        // If it's not in the addon's folder, fallback to the default .NET load context.
        // This is necessary so the addon can resolve shared framework libraries (System.Linq, etc.)
        // and our shared contract (JCMU.SDK).
        return null;
    }

    /// <summary>
    /// Overrides the resolution of native, unmanaged libraries (e.g., C++ DLLs).
    /// </summary>
    protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
    {
        string? libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);

        if (libraryPath != null)
        {
            return LoadUnmanagedDllFromPath(libraryPath);
        }

        return IntPtr.Zero;
    }
}