<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>jcmu</AssemblyName>
		<Version>1.0.5</Version>
		<AssemblyVersion>1.0.5</AssemblyVersion>
		<FileVersion>1.0.5</FileVersion>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>12</LangVersion>
		<RootNamespace>JinnDev.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<Authors>JinnDev</Authors>
		<Company>Jinn Studios</Company>
		<Product>Jinn Context Menu Utility Addon Manager</Product>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\JCMU.AddonManager\JCMU.AddonManager.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="JinnDev.Utilities.CommandLine" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
		<PackageReference Include="Serilog" Version="4.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Icons\abort.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Icons\backup.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Icons\jinn.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
